# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: true
reviews:
  profile: chill
  high_level_summary: false # don't post summary until explicitly invoked
  request_changes_workflow: false
  review_status: false
  commit_status: false
  walkthrough: false
  poem: false
  auto_review:
    enabled: true
    drafts: false # Don't review drafts automatically
    auto_incremental_review: false # always review the whole PR, not just new commits
    base_branches:
      - main
  path_filters:
    - "!**/node_modules/**"
  path_instructions:
    - path: "**/*"
      instructions: |
        Focus on inconsistencies, contradictions, edge cases and serious issues.
        Avoid commenting on minor issues such as linting, formatting and style issues.
        When providing code suggestions, use GitHub's suggestion format:
        ```suggestion
        <code changes>
        ```
    - path: "**/*.js"
      instructions: |
        CLI tooling code. Check for: missing error handling on fs operations,
        path.join vs string concatenation, proper cleanup in error paths.
        Flag any process.exit() without error message.
    - path: "src/**/workflows/**/*.md"
      instructions: |
        BMad workflow validation rules:
        - Entry files (workflow.md/workflow.yaml) MUST have `description` in frontmatter
        - Step files MUST have a `## STEP GOAL` or `## YOUR TASK` section
        - Step files SHOULD include SUCCESS METRICS and FAILURE MODES sections
        - Steps presenting user menus MUST include HALT instruction before the menu
        - Paths MUST use placeholders like `{project-root}` or `{installed_path}` instead of absolute paths
        - Steps MUST NOT instruct loading future steps before user input (just-in-time loading principle)
        - Steps MUST NOT suggest skipping steps or "optimizing execution"
        - Workflows should have 5-10 steps maximum
    - path: "src/**/workflows/**/*.yaml"
      instructions: |
        BMad workflow definition validation:
        - MUST have `name` and `description` fields
        - Step references must use relative paths or path placeholders, never absolute paths
        - If `config_source` is specified, the referenced file must exist
chat:
  auto_reply: true # Response to mentions in comments, a la @coderabbit review
issue_enrichment:
  auto_enrich:
    enabled: false # don't auto-comment on issues

